Fixed the return type of parse function of ConjunctiveGraph (Issue #939)
RDFLib/rdflib pull request #1100
Opened 2020-05-29 16:10 UTC by arnavpisces

Instead of creating a new graph and parsing changes in that (therefore changing the graph type), the parsing is done in the graph itself and a self is returned. (Similar code as parse function of class Graph).

2020-12-17 19:24 UTC, nicholascar commented
Hi @arnavpisces. Looks good overall but please can you supply tests? We really can't accept PRs to the core `graph.py` module without tests. Thanks.

2021-06-24 22:20 UTC, aucampia commented
tagging related issue #939

2021-06-25 00:03 UTC, nicholascar commented
Close/open to trigger Drone

2021-06-25 02:07 UTC, ashleysommer commented
Hi @arnavpisces are you able to rebase this PR on latest master branch? We need the Drone configs in place on your branch in order to re-run the tests.

2021-06-25 02:08 UTC, ashleysommer requested changes

2021-06-25 02:08 UTC, ashleysommer commented on rdflib/graph.py
> +
Remove these commented lines

2021-06-25 02:08 UTC, ashleysommer commented on rdflib/graph.py
> +
Remove these commented lines

2021-06-25 02:08 UTC, ashleysommer commented on rdflib/graph.py
> +            format = "application/rdf+xml"
Why is there an exception commented out here?

2022-02-12 15:30 UTC, gjhiggins commented
Timed out.

2022-02-12 15:30 UTC, closed without merging