Fix serialize with multiple disks on windows
RDFLib/rdflib pull request #1172
Opened 2020-09-28 05:59 UTC by urbanmatthias

Fixes #1170 

## Proposed Changes
I replaced the `path` variable in the `shutil.move` call with `location`.
The former is the output of an `urlencode` call, which strips the drive letter on windows machines.
If the user has multiple drives, `shutil.move` will fail if the drive letter is not there.

2020-09-30 23:44 UTC, ashleysommer commented
Hi @urbanmatthias 
I don't think this fix is quite complete, because it will now fail for UNC file locations, which used to work, like:
`file:///tmp/outfile.ttl`
In that kind of string, `scheme` is "file" and `path` is `/tmp/outfile.ttl` so `path` would be the correct variable to use.

Also, just a note, this works with Windows paths too:
`file://c:\\tmp\\outfile.ttl`
In this example, `scheme` is "file" and `path` is `c:\\tmp\\outfile.ttl` so again `path` is the correct variable to use.

A good middleground for this fix might be to test `if scheme == "file"` then use `path` otherwise, use `location`.

2020-10-01 00:16 UTC, ashleysommer requested changes

2020-10-01 00:16 UTC, ashleysommer commented on rdflib/graph.py
>              if hasattr(shutil, "move"):
```suggestion
            dest = path if scheme == "file" else location
            if hasattr(shutil, "move"):
```

2020-10-01 00:16 UTC, ashleysommer commented on rdflib/graph.py
> +                shutil.move(name, location)
```suggestion
                shutil.move(name, dest)
```

2020-10-01 00:16 UTC, ashleysommer commented on rdflib/graph.py
> +                shutil.copy(name, location)
```suggestion
                shutil.copy(name, dest)
```

2020-10-01 06:07 UTC, urbanmatthias commented
Yes you are right, thanks. I applied your suggested changes.

2020-10-01 11:00 UTC, ashleysommer commented
Need review from one more Maintainer before we can merge.

2020-10-01 19:37 UTC, nicholascar approved these changes
Looks OK to me. I folowed back through graph.py to check all the URL parsing etc. and I think this will work fine.

2020-10-01 22:13 UTC, ashleysommer commented
@nicholascar 
As far as I can tell, this is only used in the `graph.serialize()` method and only when you've set a "destination" location. So unlikely to affect anything else in graph.py or URL parsing.
I'll merge.

2020-10-01 22:16 UTC, ashleysommer approved these changes

2020-10-01 22:17 UTC, merged