Issue 1424 Resolution as suggested
RDFLib/rdflib pull request #1883
Opened 2022-05-03 21:08 UTC by vahsek300501

This is a resolution for the issue 1424. This resolution has been suggested by the David Habgood. We have added a parameter in the Graph() constructor for the recursion_depth so that the user can specify the desired recursion depth according to their needs. This way the user won't run into a stack overflow and even if they do they can come back to the code and set a bigger recursion limit to prevent it. 

However, setting the recursion depth to a particular value actually sets the default recursion depth of the system to that value. We have fixed this issue too by adding a destructor __del__() in the Graph class so that when the program ends, the recursion depth is set back to the original default value.

2022-05-03 21:09 UTC, vahsek300501 commented
Issue 1424 Resolution

2022-05-03 21:13 UTC, aucampia commented on rdflib/graph.py
> +        recursion_depth = 1000,
This will break our API and I'm not clear it is for that a good reason. At the very least the parameter should go at the end but this seems entirely too arbitrary. Without understanding what problem you are trying to fix this is difficult to see the rationale.

2022-05-03 21:15 UTC, aucampia commented on .gitignore
> +**/.DS_Store
This should go in `$XDG_CONFIG_HOME/git/ignore` ([ref](https://git-scm.com/docs/gitignore), this is ~/.config/git/ignore on Linux by default)

2022-05-03 21:17 UTC, aucampia commented
The right solution here seems to be to just avoid recursion wherever it is happening.

2022-05-03 21:20 UTC, aucampia commented
The first step in fixing this is reproducing it, we should have a test that fails for this, and then I think we should consider changing the parsing algorithm to not be recursive.

2022-05-03 21:22 UTC, Priyansh19077 commented on rdflib/graph.py
> +        recursion_depth = 1000,
We can move the parameter to the very end. 
As far as the problem is concerned, in the issue (1424: https://github.com/RDFLib/rdflib/issues/1424) it is stated that in case the size of the graph is very large the program runs into a stack overflow. We have solved this by allowing the user to give an input of the value of recursion depth they would like for their code. As suggested by you, the last time we had raised a PR (1822: https://github.com/RDFLib/rdflib/pull/1822#discussion_r851310616), we have made the same changes.

2022-05-03 21:26 UTC, Priyansh19077 commented
> The first step in fixing this is reproducing it, we should have a test that fails for this, and then I think we should consider changing the parsing algorithm to not be recursive.

The issue can be reproduced as follows: 
from rdflib import Graph
g=Graph().parse('https://gist.githubusercontent.com/recalcitrantsupplant/5b5916f5de2fccd47252c3b54cc064e2/raw/3982bb2b4129607572a1226fef907a18de42d089/long_linked_list.xml', format='xml')
g.serialize(format='turtle')

This gets resolved if we run pass the recursion depth as 100000
from rdflib import Graph
g=Graph(recursion_depth=100000).parse('https://gist.githubusercontent.com/recalcitrantsupplant/5b5916f5de2fccd47252c3b54cc064e2/raw/3982bb2b4129607572a1226fef907a18de42d089/long_linked_list.xml', format='xml')
g.serialize(format='turtle')

2022-05-03 21:27 UTC, aucampia commented on rdflib/graph.py
> +        recursion_depth = 1000,
Maybe you misunderstood my point, anyone can at any point call `sys.setrecursionlimit()` with any value they want, and if someone wants a different recursion limit they should set it appropriately. The underlying issue though is that python does not really work well with indefinite recursion, and if we have some algorithm that does do indefinite recursion then using `sys.setrecursionlimit()` will just be a stopgap anyway, as you can only make it so large. The only real solution that is appropriate in RDFLib to this issue from my point of view is to change to a non recursive parsing implementation.

2022-05-03 21:31 UTC, aucampia commented
By reproducing it I mean in RDFLib tests. In general we expect that all fixes are accompanied with test that would fail without the fix: 

https://rdflib.readthedocs.io/en/latest/developers.html#pull-requests-guidelines

> Changes that have a runtime impact are covered by unit tests.
> 
> There should either be existing tests that cover the changed code and behaviour, or the PR should include tests. For more information about what is considered adequate testing see the [Tests section](https://rdflib.readthedocs.io/en/latest/developers.html#tests).

https://rdflib.readthedocs.io/en/latest/developers.html#tests

> Tests that you add should show how your new feature or bug fix is doing what you say it is doing: if you remove your enhancement, your new tests should fail!

2022-05-03 21:32 UTC, aucampia commented on rdflib/graph.py
> +        recursion_depth = 1000,
To be clear though, by non recursive I mean in terms python function calls - the actual parsing algorithm can still be recursive as long as it is implemented using loops instead of python recursion.

2022-05-08 15:15 UTC, aucampia requested changes
@Priyansh19077 there may be other opinions from other maintainers, but I would not be comfortable with approving a fix for this issue that is based on playing around with `sys.setrecursionlimit`. I could possibly consider a PR that adds a way to set `sys.setrecursionlimit` for our command line tools (e.g. rdfpipe).

Further, this PR does not add a tests for the issue, so there is little to salvage. 

Happy to review once tests are in place with a solution not based on `sys.setrecursionlimit`.

2022-05-11 22:27 UTC, aucampia commented
Will close this PR if there is nothing further by 2022-05-15

2022-05-14 17:55 UTC, aucampia commented
Closing as the solution proposed in this PR can already easily be implemented in code by users of this library if they want using functionality already present in python.

2022-05-14 17:55 UTC, closed without merging