Issue 166 in SPARQLWrapper solved
RDFLib/rdflib pull request #1900
Opened 2022-05-09 08:52 UTC by PritishWadhwa

The order of ResultRows for a SELECT * query was randomized and was changing. This is unexpected because other SPARQL engines seem to generally apply the order of variables as they occur in the WHERE block.

Sample code:

query="SELECT * { ?a ?b ?c } LIMIT 10"
qres=g.query(query)
print(qres.vars)

Expected output:
[rdflib.term.Variable('a'), rdflib.term.Variable('b'), rdflib.term.Variable('c')]

Real output:
[rdflib.term.Variable('c'), rdflib.term.Variable('a'), rdflib.term.Variable('b')] (first run)
[rdflib.term.Variable('a'), rdflib.term.Variable('b'), rdflib.term.Variable('c')] (second run)
[rdflib.term.Variable('b'), rdflib.term.Variable('a'), rdflib.term.Variable('c')] (third run)
[rdflib.term.Variable('a'), rdflib.term.Variable('c'), rdflib.term.Variable('b')] (fourth run)
[you get the idea]

(Tested on the HDT edition of DBpedia 2016, created with g = rdflib.Graph(store=rdflib_hdt.HDTStore(rdf_file)), but that shouldn't matter.)

This was corrected without interfering with the time complexity and the output is now as it should be (as shown in the expected output)

2022-05-09 12:40 UTC, aucampia commented
All changes I see is the addition of a commented function.

2022-05-09 12:52 UTC, PritishWadhwa commented
> All changes I see is the addition of a commented function, maybe something is missing? If you are still working on a PR best to mark it as draft.

Yeah I was finalizing something, it is done now

2022-05-09 13:18 UTC, aucampia commented
> > All changes I see is the addition of a commented function, maybe something is missing? If you are still working on a PR best to mark it as draft.
> 
> Yes I was finalizing something, it is done now

Many tests fail now:

https://drone.rdflib.ashs.dev/RDFLib/rdflib/1685/1/2
```
= 56 failed, 5417 passed, 2 skipped, 117 xfailed, 1 xpassed, 50 warnings in 264.39s (0:04:24) =
```

Also this PR will need a test that reproduces the broken behavior for it to be merged.

2022-05-10 06:14 UTC, PritishWadhwa commented
I have made the changes, now the tests which were earlier failing should not fail. I have also added the test file for reproducing the broken behavior.

2022-05-10 06:27 UTC, ananya2711 approved these changes

2022-05-10 09:47 UTC, gjhiggins commented
Looking good, all that's left to do in order to satisfy the automated contrib tests is to black the test file.

2022-05-10 13:30 UTC, PritishWadhwa commented
> Looking good, all that's left to do in order to satisfy the automated contrib tests is to black the test file.

Hi. Can you please explain what you mean by "blacking the test file" and how to do it? I am fairly new to open source contribution and haven't seen this term before.

2022-05-10 14:23 UTC, aucampia commented
> pre-commit.ci autofix

@PritishWadhwa this is what @gjhiggins  meant

I will review this when I can, before Sunday if possible.

2022-05-10 14:25 UTC, aucampia commented on test/test_issues/test_issue166.py
> +def test_issue_166() -> None:
Just briefly, I would much rather prefer this goes into https://github.com/RDFLib/rdflib/blob/eba13739e1d24b3e52697a1ec9545a361116951f/test/test_sparql/test_sparql.py#L694-L727

2022-05-11 22:08 UTC, aucampia commented
Appologies but this will only be reviewed in W20 as #1891 is taking most of my time and I have other priorities also.

2022-05-12 01:00 UTC, PritishWadhwa commented
> Appologies but this will only be reviewed in W20 as #1891 is taking most of my time and I have other priorities also.

Sure, No worries!

2022-05-12 15:53 UTC, aucampia commented
Just a note, to link this PR to an issue please see:
- [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

The way you are doing it makes more involved to find the issue you are referring to.

2022-05-13 20:32 UTC, aucampia commented
I'm going to first merge typing from https://github.com/RDFLib/rdflib/pull/1850 before merging these fixes, this will be in smallish PRs like:

- https://github.com/RDFLib/rdflib/pull/1926

Once these are merged  you should rebase this.

In general though the tests should still be integrated.

Furthermore, I think it may be better to use dict or OrderedDict instead of list and a set: https://stackoverflow.com/a/53657523/1598080

2022-05-14 05:28 UTC, PritishWadhwa commented
> I'm going to first merge typing from #1850 before merging these fixes, this will be in smallish PRs like:
> 
> * [Add typing for `rdflib/plugins/sparql` #1926](https://github.com/RDFLib/rdflib/pull/1926)
> 
> Once these are merged you should rebase this.
> 
> In general though the tests should still be integrated.
> 
> Furthermore, I think it may be better to use dict or OrderedDict instead of list and a set: https://stackoverflow.com/a/53657523/1598080

Sure

2022-05-14 21:27 UTC, aucampia requested changes
See previous comments.

2022-05-15 14:11 UTC, aucampia commented
Please rebase this branch onto master or merge master into this branch.

2022-07-22 01:18 UTC, aucampia commented
If there is nothing further on this PR I will close it.

2022-07-29 02:12 UTC, aucampia commented
Closing this PR due to inactivity, feel free to open it again if you continue working on it again.

2022-07-29 02:13 UTC, aucampia commented
Closing this PR due to inactivity, feel free to open it again if you continue working on it again.

2022-07-29 02:13 UTC, closed without merging